Adjusted script indent

diff --git a/.github/workflows/deploy-vm.yaml b/.github/workflows/deploy-vm.yaml
--- a/.github/workflows/deploy-vm.yaml
+++ b/.github/workflows/deploy-vm.yaml
@@ -13,56 +13,56 @@ jobs:
           host: ${{secrets.SSH_HOST}}
           key: ${{secrets.VM_KEY}}
           username: ${{secrets.VM_USER}}
-        script: |
-          docker compose down
-          rm -rf deploy
-          mkdir deploy
-          cd deploy
-          if ! git clone git@github.com:aprask/GameScout.git; then
-            echo "Failed to clone repository"
-            exit 1
-          fi
-          echo 'Cloned repo'
-          cd scripts
-          chmod +x deploy-init.sh
-          ./deploy-init.sh
-          echo 'Downloaded depedencies'
-          cd ../client
-          touch .env
-          cat > .env << EOF
-          VITE_PROD_URL=${{secrets.VITE_PROD_URL}}
-          VITE_APP_ENV=${{secrets.VITE_APP_ENV}}
-          VITE_API_MANAGEMENT_KEY=${{secrets.VITE_API_MANAGEMENT_KEY}}
-          EOF
-          cd ../server
-          touch .env
-          cat > .env << EOF
-          API_MANAGEMENT_KEY=${{secrets.VITE_API_MANAGEMENT_KEY}}
-          DEV_HOST=${{secrets.DEV_HOST}}
-          IGDB_CLIENT=${{secrets.IGDB_CLIENT}}
-          IGDB_SECRET=${{secrets.IGDB_SECRET}}
-          ADMIN_SECRET=${{secrets.ADMIN_SECRET}}
-          RABBIT_HOST=${{secrets.RABBIT_HOST}}
-          RABBIT_PORT=${{secrets.RABBIT_PORT}}
-          RABBIT_USERNAME=${{secrets.RABBIT_USERNAME}}
-          RABBIT_PASSWORD=${{secrets.RABBIT_PASSWORD}}
-          POSTGRES_USER=${{secrets.POSTGRES_USER}}
-          POSTGRES_PASSWORD=${{secrets.POSTGRES_PASSWORD}}
-          POSTGRES_DB=${{secrets.POSTGRES_DB}}
-          APP_ENV=${{secrets.APP_ENV}}
-          EOF
-          cd ../scheduler-proc
-          touch .env
-          cat > .env << EOF
-          IGDB_CLIENT=${{secrets.IGDB_CLIENT}}
-          IGDB_SECRET=${{secrets.IGDB_SECRET}}
-          RABBIT_HOST=${{secrets.RABBIT_HOST}}
-          RABBIT_PORT=${{secrets.RABBIT_PORT}}
-          RABBIT_USERNAME=${{secrets.RABBIT_USERNAME}}
-          RABBIT_PASSWORD=${{secrets.RABBIT_PASSWORD}}
-          APP_ENV=${{secrets.APP_ENV}}
-          EOF
-          cd ..
-          echo 'Starting containers...'
-          docker compose -f docker-compose.yaml up --build -d
-          echo 'Deployment complete'
+          script: |
+            docker compose down
+            rm -rf deploy
+            mkdir deploy
+            cd deploy
+            if ! git clone git@github.com:aprask/GameScout.git; then
+              echo "Failed to clone repository"
+              exit 1
+            fi
+            echo 'Cloned repo'
+            cd scripts
+            chmod +x deploy-init.sh
+            ./deploy-init.sh
+            echo 'Downloaded depedencies'
+            cd ../client
+            touch .env
+            cat > .env << EOF
+            VITE_PROD_URL=${{secrets.VITE_PROD_URL}}
+            VITE_APP_ENV=${{secrets.VITE_APP_ENV}}
+            VITE_API_MANAGEMENT_KEY=${{secrets.VITE_API_MANAGEMENT_KEY}}
+            EOF
+            cd ../server
+            touch .env
+            cat > .env << EOF
+            API_MANAGEMENT_KEY=${{secrets.VITE_API_MANAGEMENT_KEY}}
+            DEV_HOST=${{secrets.DEV_HOST}}
+            IGDB_CLIENT=${{secrets.IGDB_CLIENT}}
+            IGDB_SECRET=${{secrets.IGDB_SECRET}}
+            ADMIN_SECRET=${{secrets.ADMIN_SECRET}}
+            RABBIT_HOST=${{secrets.RABBIT_HOST}}
+            RABBIT_PORT=${{secrets.RABBIT_PORT}}
+            RABBIT_USERNAME=${{secrets.RABBIT_USERNAME}}
+            RABBIT_PASSWORD=${{secrets.RABBIT_PASSWORD}}
+            POSTGRES_USER=${{secrets.POSTGRES_USER}}
+            POSTGRES_PASSWORD=${{secrets.POSTGRES_PASSWORD}}
+            POSTGRES_DB=${{secrets.POSTGRES_DB}}
+            APP_ENV=${{secrets.APP_ENV}}
+            EOF
+            cd ../scheduler-proc
+            touch .env
+            cat > .env << EOF
+            IGDB_CLIENT=${{secrets.IGDB_CLIENT}}
+            IGDB_SECRET=${{secrets.IGDB_SECRET}}
+            RABBIT_HOST=${{secrets.RABBIT_HOST}}
+            RABBIT_PORT=${{secrets.RABBIT_PORT}}
+            RABBIT_USERNAME=${{secrets.RABBIT_USERNAME}}
+            RABBIT_PASSWORD=${{secrets.RABBIT_PASSWORD}}
+            APP_ENV=${{secrets.APP_ENV}}
+            EOF
+            cd ..
+            echo 'Starting containers...'
+            docker compose -f docker-compose.yaml up --build -d
+            echo 'Deployment complete'
